[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vlad", email = "hudakovvlad8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "blessed>=1.45.0",
    "dotenv>=0.9.9",
    "google-genai>=2.10.0",
    "numpy>=2.5.0",
]

[project.scripts]
jarvis = "jarvis:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
